[package]
name = "launch-rs"
version = "0.1.0"
authors = ["James Munns <james.munns@gmail.com>"]

[dependencies]
midir = { git = "https://github.com/Boddlnagg/midir", branch = "port-ids" }
launchpad = { version = "*", path = "lib" }
clap = "*"
